import { render } from "solid-js/web";
import { Route, Router } from "@solidjs/router";
import { DocsLayout, DocsProvider } from "@swifty.js/docs";

// Auto-generated by defineConfig()
import {
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@swifty-docs/generated";

// CSS
import "./main.css";

/**
 * App entry. The generated module provides the site config, the per-route
 * content loader, and the lazy search index; the theme renders everything
 * inside a single catch-all route (the layout stays mounted across
 * navigation and only the content column swaps).
 */
render(
  () => (
    <DocsProvider
      config={docsConfig}
      loadContent={loadContent}
      getSearchIndex={getSearchIndex}
    >
      <Router>
        <Route path="/*all" component={DocsLayout} />
      </Router>
    </DocsProvider>
  ),
  document.getElementById("app")!,
);
