import { render } from "preact";
import { Router, Route } from "wouter-preact";
import { DocsLayout, DocsProvider } from "@swifty.js/docs";

// Auto-generated by defineConfig()
import {
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@swifty-docs/generated";

// CSS
import "./main.css";

render(
  <DocsProvider
    config={docsConfig}
    loadContent={loadContent}
    getSearchIndex={getSearchIndex}
  >
    <Router>
      <Route path="/*" component={DocsLayout} />
    </Router>
  </DocsProvider>,
  document.getElementById("app")!,
);
