import {
  Search,
  Menu,
  X,
  Sun,
  Moon,
  ChevronDown,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  CornerDownLeft,
  Copy,
  Check,
  List,
  FileText,
  Compass,
} from "lucide-static";

export const icons = {
  search: Search,
  menu: Menu,
  x: X,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  cornerDownLeft: CornerDownLeft,
  copy: Copy,
  check: Check,
  list: List,
  fileText: FileText,
  compass: Compass,
} as const;
